// Code generated by machine generator; DO NOT EDIT.

use crate::core::rfc2865;

pub const NAS_PORT_TYPE_PP_PO_A: rfc2865::NasPortType = 30;
pub const NAS_PORT_TYPE_PP_PO_EO_A: rfc2865::NasPortType = 31;
pub const NAS_PORT_TYPE_PP_PO_EO_E: rfc2865::NasPortType = 32;
pub const NAS_PORT_TYPE_PP_PO_EO_VLAN: rfc2865::NasPortType = 33;
pub const NAS_PORT_TYPE_PP_PO_EO_QIN_Q: rfc2865::NasPortType = 34;
