// Code generated by machine generator; DO NOT EDIT.

//! Utility for rfc4603 packet.
//!
//! This module handles the packet according to the following definition:
//! ```text
//! //! # -*- text -*-
//! # Copyright (C) 2020 The FreeRADIUS Server project and contributors
//! # This work is licensed under CC-BY version 4.0 https://creativecommons.org/licenses/by/4.0
//! # Version $Id$
//! ##############################################################################
//! #
//! #	Attributes and values defined in RFC 4603.
//! #	http://www.ietf.org/rfc/rfc4603.txt
//! #
//! #	$Id$
//! #
//! ##############################################################################
//!
//! VALUE	NAS-Port-Type			PPPoA			30
//! VALUE	NAS-Port-Type			PPPoEoA			31
//! VALUE	NAS-Port-Type			PPPoEoE			32
//! VALUE	NAS-Port-Type			PPPoEoVLAN		33
//! VALUE	NAS-Port-Type			PPPoEoQinQ		34
//!
//! ```

use crate::core::rfc2865;

pub const NAS_PORT_TYPE_PP_PO_A: rfc2865::NasPortType = 30;
pub const NAS_PORT_TYPE_PP_PO_EO_A: rfc2865::NasPortType = 31;
pub const NAS_PORT_TYPE_PP_PO_EO_E: rfc2865::NasPortType = 32;
pub const NAS_PORT_TYPE_PP_PO_EO_VLAN: rfc2865::NasPortType = 33;
pub const NAS_PORT_TYPE_PP_PO_EO_QIN_Q: rfc2865::NasPortType = 34;
