// Code generated by machine generator; DO NOT EDIT.

use crate::core::avp::{AVPError, AVPType, AVP};
use crate::core::packet::Packet;

pub const NAS_FILTER_RULE_TYPE: AVPType = 92;
pub fn delete_nas_filter_rule(packet: &mut Packet) {
    packet.delete(NAS_FILTER_RULE_TYPE);
}
pub fn add_nas_filter_rule(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(NAS_FILTER_RULE_TYPE, value));
}
pub fn lookup_nas_filter_rule(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(NAS_FILTER_RULE_TYPE)
        .map(|v| v.encode_string())
}
pub fn lookup_all_nas_filter_rule(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(NAS_FILTER_RULE_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}
