// Code generated by machine generator; DO NOT EDIT.

//! Utility for rfc5176 packet.
//!
//! This module handles the packet according to the following definition:
//! ```text
//! //! # -*- text -*-
//! # Copyright (C) 2020 The FreeRADIUS Server project and contributors
//! # This work is licensed under CC-BY version 4.0 https://creativecommons.org/licenses/by/4.0
//! # Version $Id$
//! #
//! #    Attributes and values defined in RFC 5176.
//! #    http://www.ietf.org/rfc/rfc5176.txt
//! #
//! #    $Id$
//! #
//! VALUE    Error-Cause            Invalid-Attribute-Value    407
//! VALUE    Error-Cause            Multiple-Session-Selection-Unsupported    508
//! ```

use crate::core::rfc3576;

pub const ERROR_CAUSE_INVALID_ATTRIBUTE_VALUE: rfc3576::ErrorCause = 407;
pub const ERROR_CAUSE_MULTIPLE_SESSION_SELECTION_UNSUPPORTED: rfc3576::ErrorCause = 508;
