// Code generated by machine generator; DO NOT EDIT.

pub type AcctTerminateCause = u32;
pub const ACCT_TERMINATE_CAUSE_SUPPLICANT_RESTART: AcctTerminateCause = 19;
pub const ACCT_TERMINATE_CAUSE_REAUTHENTICATION_FAILURE: AcctTerminateCause = 20;
pub const ACCT_TERMINATE_CAUSE_PORT_REINIT: AcctTerminateCause = 21;
pub const ACCT_TERMINATE_CAUSE_PORT_DISABLED: AcctTerminateCause = 22;

pub type NasPortType = u32;
pub const NAS_PORT_TYPE_TOKEN_RING: NasPortType = 20;
pub const NAS_PORT_TYPE_FDDI: NasPortType = 21;

pub type TunnelType = u32;
pub const TUNNEL_TYPE_VLAN: TunnelType = 13;
