// Code generated by machine generator; DO NOT EDIT.

pub type NasPortType = u32;
pub const NAS_PORT_TYPE_PP_PO_A: NasPortType = 30;
pub const NAS_PORT_TYPE_PP_PO_EO_A: NasPortType = 31;
pub const NAS_PORT_TYPE_PP_PO_EO_E: NasPortType = 32;
pub const NAS_PORT_TYPE_PP_PO_EO_VLAN: NasPortType = 33;
pub const NAS_PORT_TYPE_PP_PO_EO_QIN_Q: NasPortType = 34;
