// Code generated by machine generator; DO NOT EDIT.

use crate::attribute::Attribute;
use crate::attributes::AVPType;
use crate::packet::Packet;

pub type AcctStatusType = u32;
pub const ACCT_STATUS_TYPE_TUNNEL_START: AcctStatusType = 9;
pub const ACCT_STATUS_TYPE_TUNNEL_STOP: AcctStatusType = 10;
pub const ACCT_STATUS_TYPE_TUNNEL_REJECT: AcctStatusType = 11;
pub const ACCT_STATUS_TYPE_TUNNEL_LINK_START: AcctStatusType = 12;
pub const ACCT_STATUS_TYPE_TUNNEL_LINK_STOP: AcctStatusType = 13;
pub const ACCT_STATUS_TYPE_TUNNEL_LINK_REJECT: AcctStatusType = 14;

pub const ACCT_TUNNEL_CONNECTION_TYPE: AVPType = 68;
pub fn delete_acct_tunnel_connection(packet: &mut Packet) {
    packet.delete(ACCT_TUNNEL_CONNECTION_TYPE);
}
pub fn lookup_acct_tunnel_connection(packet: &Packet) -> Option<&Attribute> {
    packet.lookup(ACCT_TUNNEL_CONNECTION_TYPE)
}
pub fn lookup_all_acct_tunnel_connection(packet: &Packet) -> Vec<&Attribute> {
    packet.lookup_all(ACCT_TUNNEL_CONNECTION_TYPE)
}
pub fn add_acct_tunnel_connection(packet: &mut Packet, value: &str) {
    let attr = Attribute::from_string(value);
    packet.add(ACCT_TUNNEL_CONNECTION_TYPE, &attr);
}

pub const ACCT_TUNNEL_PACKETS_LOST_TYPE: AVPType = 86;
pub fn delete_acct_tunnel_packets_lost(packet: &mut Packet) {
    packet.delete(ACCT_TUNNEL_PACKETS_LOST_TYPE);
}
pub fn lookup_acct_tunnel_packets_lost(packet: &Packet) -> Option<&Attribute> {
    packet.lookup(ACCT_TUNNEL_PACKETS_LOST_TYPE)
}
pub fn lookup_all_acct_tunnel_packets_lost(packet: &Packet) -> Vec<&Attribute> {
    packet.lookup_all(ACCT_TUNNEL_PACKETS_LOST_TYPE)
}
pub fn add_acct_tunnel_packets_lost(packet: &mut Packet, value: u32) {
    let attr = Attribute::from_u32(value);
    packet.add(ACCT_TUNNEL_PACKETS_LOST_TYPE, &attr);
}
